server:
  port: 8080
  host: localhost
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${server.host}/chatroom?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: wx
      max-wait: 3000
  redis:
    port: 6379        #redis端口
    host: ${server.host}   #主机ip
    database: 0       #默认数据库
    timeout: 1800000  #连接超时时间
    password: wangxing #Redis数据库密码
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1  #最大等待时间
        max-idle: 5
        min-idle: 0
  data:
    mongodb:
      host: localhost
      database: admin
      port: 27017
      username: root
      password: yourpassword
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
